// This file contains the product data for the website

export const products = [
  {
    id: "7",
    title: "Serene Lake at Sunset",
    category: "Original Watercolor",
    price: "2,200.00",
    description:
      "A tranquil watercolor landscape capturing the serene beauty of a lake at sunset. The painting features a solitary tree silhouette against a backdrop of distant mountains, with a vibrant turquoise lake in the foreground. The sky transitions from soft blue to warm peach tones, creating a peaceful atmosphere.",
    details: "Watercolor on paper\nDimensions: 30 x 40 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/watercolor-landscape-lake.png", "/images/watercolor-landscape-lake.png"],
    related: ["8", "9", "14"],
  },
  {
    id: "8",
    title: "Mountain Valley Vista",
    category: "Original Watercolor",
    price: "2,400.00",
    description:
      "A dramatic watercolor landscape depicting a mountainous valley at dawn or dusk. The painting showcases rugged cliffs and rock formations with a distant valley view. The sky features soft blue and peach tones that complement the earthy colors of the mountains, creating a sense of depth and atmosphere.",
    details: "Watercolor on paper\nDimensions: 30 x 40 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/watercolor-mountain-valley.png", "/images/watercolor-mountain-valley.png"],
    related: ["7", "9", "15"],
  },
  {
    id: "9",
    title: "Golden Fields Panorama",
    category: "Original Watercolor",
    price: "2,600.00",
    description:
      "A breathtaking panoramic watercolor landscape depicting golden fields and farmland stretching toward distant blue mountains. The painting captures the warm amber tones of the countryside contrasted with a dramatic blue sky that transitions from deep azure at the top to lighter hues near the horizon. The artist masterfully conveys depth and atmosphere through subtle color gradations and loose, expressive brushwork.",
    details: "Watercolor on paper\nDimensions: 35 x 45 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/watercolor-golden-fields.png", "/images/watercolor-golden-fields.png"],
    related: ["7", "8", "14"],
  },
  {
    id: "14",
    title: "Tranquil Lakeside",
    category: "Original Watercolor",
    price: "2,300.00",
    description:
      "A peaceful watercolor landscape depicting a serene lake framed by trees. The composition masterfully captures the reflective quality of the water and the lush vegetation surrounding it. The artist uses a harmonious palette of blues and greens with touches of earth tones to create a sense of depth and tranquility. The delicate brushwork in the foliage and the subtle gradations in the water surface demonstrate exceptional technical skill.",
    details: "Watercolor on paper\nDimensions: 28 x 38 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/watercolor-lake-view.png", "/images/watercolor-lake-view.png"],
    related: ["7", "9", "15"],
  },
  {
    id: "15",
    title: "Mountain Majesty",
    category: "Original Watercolor",
    price: "2,500.00",
    description:
      "A dramatic watercolor landscape showcasing the imposing beauty of a mountain range. The composition features bold cliffs and rocky outcroppings in the foreground, with softer, misty mountains receding into the distance. The artist skillfully employs a palette of blues, purples, and greens to convey the grandeur and scale of the scene. The dynamic brushwork in the foreground cliffs contrasts beautifully with the delicate treatment of the distant mountains and sky.",
    details: "Watercolor on paper\nDimensions: 30 x 42 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/watercolor-mountain-cliff.png", "/images/watercolor-mountain-cliff.png"],
    related: ["8", "14", "7"],
  },
  {
    id: "16",
    title: "Sketchbook: Expressive Portrait I",
    category: "Sketchbook Study",
    price: "not-for-sale",
    description: "",
    details: "Pen on paper\nDimensions: 21 x 29.7 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/sketch-face-1.png", "/images/sketch-face-1.png"],
    related: ["17", "18", "19"],
  },
  {
    id: "17",
    title: "Sketchbook: Expressive Portrait II",
    category: "Sketchbook Study",
    price: "not-for-sale",
    description: "",
    details: "Pen on paper\nDimensions: 21 x 29.7 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/sketch-face-2.png", "/images/sketch-face-2.png"],
    related: ["16", "18", "20"],
  },
  {
    id: "18",
    title: "Sketchbook: Expressive Portrait III",
    category: "Sketchbook Study",
    price: "not-for-sale",
    description: "",
    details: "Pen on paper\nDimensions: 21 x 29.7 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/sketch-face-3.png", "/images/sketch-face-3.png"],
    related: ["16", "17", "21"],
  },
  {
    id: "19",
    title: "Sketchbook: Expressive Portrait IV",
    category: "Sketchbook Study",
    price: "not-for-sale",
    description: "",
    details: "Pen on paper\nDimensions: 21 x 29.7 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/sketch-face-4.png", "/images/sketch-face-4.png"],
    related: ["16", "20", "22"],
  },
  {
    id: "20",
    title: "Sketchbook: Expressive Portrait V",
    category: "Sketchbook Study",
    price: "not-for-sale",
    description: "",
    details: "Pen on paper\nDimensions: 21 x 29.7 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/sketch-face-5.png", "/images/sketch-face-5.png"],
    related: ["17", "19", "23"],
  },
  {
    id: "21",
    title: "Sketchbook: Expressive Portrait VI",
    category: "Sketchbook Study",
    price: "not-for-sale",
    description: "",
    details: "Pen on paper\nDimensions: 21 x 29.7 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/sketch-face-6.png", "/images/sketch-face-6.png"],
    related: ["18", "20", "24"],
  },
  {
    id: "22",
    title: "Sketchbook: Expressive Portrait VII",
    category: "Sketchbook Study",
    price: "not-for-sale",
    description: "",
    details: "Pen on paper\nDimensions: 21 x 29.7 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/sketch-face-7.png", "/images/sketch-face-7.png"],
    related: ["19", "21", "25"],
  },
  {
    id: "23",
    title: "Sketchbook: Expressive Portrait VIII",
    category: "Sketchbook Study",
    price: "not-for-sale",
    description: "",
    details: "Pen on paper\nDimensions: 21 x 29.7 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/sketch-face-8.png", "/images/sketch-face-8.png"],
    related: ["20", "22", "16"],
  },
  {
    id: "24",
    title: "Sketchbook: Expressive Portrait IX",
    category: "Sketchbook Study",
    price: "not-for-sale",
    description: "",
    details: "Pen on paper\nDimensions: 21 x 29.7 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/sketch-face-9.png", "/images/sketch-face-9.png"],
    related: ["21", "23", "17"],
  },
  {
    id: "25",
    title: "Sketchbook: Expressive Portrait X",
    category: "Sketchbook Study",
    price: "not-for-sale",
    description: "",
    details: "Pen on paper\nDimensions: 21 x 29.7 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/sketch-face-10.png", "/images/sketch-face-10.png"],
    related: ["22", "24", "18"],
  },
  {
    id: "26",
    title: "Soft and Fresh Breeze Under the Shade of The Tree",
    category: "Original Watercolor",
    price: "2,800.00",
    description:
      "A luminous watercolor landscape featuring a majestic tree framing a pastoral scene. The artist masterfully captures the interplay of light and shadow through the canopy, with vibrant greens ranging from lime to deep forest tones. The composition draws the eye from the detailed foreground tree through the sun-dappled meadow to the misty blue mountains in the distance, creating a sense of depth and tranquility that invites contemplation.",
    details: "SOLD\nWatercolor on paper\nDimensions: 10 x 14 in\nYear: 2020\nSigned by the artist",
    images: ["/images/watercolor-tree-landscape.png", "/images/watercolor-tree-landscape.png"],
    related: ["7", "14", "15"],
  },
  {
    id: "27",
    title: "Agricultural Fields",
    category: "Original Watercolor",
    price: "2,700.00",
    description:
      "A masterful watercolor depicting the geometric beauty of cultivated farmland. The composition showcases parallel furrows stretching toward distant blue mountains, creating strong linear perspective that draws the viewer into the landscape. The artist employs a rich palette of earth tones—browns, ochres, and greens—contrasted against the cool blues of the mountains and sky. The technique demonstrates exceptional control of watercolor, with precise wet-on-dry applications creating the structured field patterns while maintaining the medium's characteristic transparency and luminosity.",
    details: "Watercolor on paper\nDimensions: 35 x 50 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/watercolor-agricultural-fields.png", "/images/watercolor-agricultural-fields.png"],
    related: ["9", "26", "28"],
  },
  {
    id: "28",
    title: "Rolling Hills Vista",
    category: "Original Watercolor",
    price: "2,900.00",
    description:
      "A breathtaking watercolor landscape capturing the undulating beauty of rolling countryside beneath a dramatic sky. The composition features layers of hills receding into the distance, each rendered in progressively cooler tones to create atmospheric perspective. The sky dominates the upper portion with bold blue washes and strategic white paper reserves suggesting billowing clouds. The foreground hills are painted in warm earth tones—ochres, umbers, and muted greens—that gradually transition to cooler blues and purples in the distance, demonstrating the artist's sophisticated understanding of color temperature and spatial relationships.",
    details: "Watercolor on paper\nDimensions: 38 x 55 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/watercolor-rolling-hills.png", "/images/watercolor-rolling-hills.png"],
    related: ["15", "27", "9"],
  },
  {
    id: "29",
    title: "Solitary Reflection",
    category: "Original Watercolor",
    price: "2,400.00",
    description:
      "A contemplative watercolor landscape featuring a lone bare tree emerging from tranquil waters, set against a backdrop of rolling hills and a dramatic cloudy sky. The composition masterfully balances the stark silhouette of the leafless tree with the soft, atmospheric treatment of the surrounding landscape. The artist employs a subtle palette of blues, greens, and earth tones, with the sky rendered in delicate washes that transition from deep blue-gray clouds to lighter tones near the horizon. The water's surface reflects the sky and surrounding landscape, creating a sense of depth and serenity that speaks to themes of solitude and reflection.",
    details: "Watercolor on paper\nDimensions: 30 x 40 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/watercolor-solitary-tree.png", "/images/watercolor-solitary-tree.png"],
    related: ["7", "14", "26"],
  },
  {
    id: "30",
    title: "Coastal Abstraction",
    category: "Original Watercolor",
    price: "2,650.00",
    description:
      "An evocative abstract watercolor landscape that captures the essence of a coastal scene through expressive brushwork and a rich, moody palette. The composition features dramatic dark formations suggesting rocky cliffs or mountains that frame a distant view of what appears to be water, indicated by a subtle turquoise accent on the horizon. The artist employs a sophisticated range of browns, purples, and golden tones that blend and diffuse in the characteristic manner of watercolor, creating areas of depth and luminosity. The loose, gestural approach allows the viewer's imagination to complete the scene, inviting personal interpretation and emotional response.",
    details: "Watercolor on paper\nDimensions: 32 x 48 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/watercolor-abstract-landscape.png", "/images/watercolor-abstract-landscape.png"],
    related: ["15", "28", "27"],
  },
  {
    id: "31",
    title: "Blue Harmony Study",
    category: "Abstract Study",
    price: "1,950.00",
    description:
      "A delicate monochromatic watercolor study exploring organic forms in various shades of blue. The composition features fluid, gestural brushwork that suggests hands or marine creatures in motion, creating a sense of gentle movement across the paper. The artist masterfully employs the transparency of watercolor to build layers of varying intensity, from pale washes to deeper indigo tones. The negative space of the white paper plays an essential role in the composition, creating a luminous quality that enhances the ethereal nature of the forms. Small hexagonal patterns in the corners add a subtle geometric counterpoint to the flowing organic shapes.",
    details: "Watercolor on paper\nDimensions: 24 x 32 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/watercolor-blue-abstract.png", "/images/watercolor-blue-abstract.png"],
    related: ["32", "30", "9"],
  },
  {
    id: "32",
    title: "Chromatic Explosion",
    category: "Original Watercolor",
    price: "2,350.00",
    description:
      "A vibrant, energetic abstract watercolor that celebrates the expressive potential of color and spontaneous mark-making. The composition bursts with a dynamic interplay of pink, yellow, blue, green, and black elements that dance across the paper. Bold splashes and splatters contrast with more controlled brushwork, creating a tension between chaos and intention. The artist employs various watercolor techniques—wet-on-wet, dry brush, and splatter—to achieve a rich variety of textures and effects. Dark calligraphic marks anchor the composition, while transparent washes create depth and luminosity. This piece embodies the joy of artistic experimentation and the emotional power of abstract expression.",
    details: "Watercolor and mixed media on paper\nDimensions: 26 x 38 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/watercolor-colorful-abstract.png", "/images/watercolor-colorful-abstract.png"],
    related: ["31", "30", "9"],
  },
  // Nuevas acuarelas urbanas monocromáticas
  {
    id: "33",
    title: "Urban Twilight",
    category: "Original Watercolor",
    price: "2,100.00",
    description:
      "A masterful monochromatic watercolor capturing the atmospheric quality of a European town at twilight. The composition features a prominent church spire that rises above the surrounding buildings, creating a focal point that anchors the scene. Using only shades of gray, the artist conveys a remarkable sense of depth and mood, with the buildings softly reflected in the foreground water. The delicate handling of values creates a dreamy, nostalgic quality that transports the viewer to quiet streets at dusk. The minimal palette demonstrates how tonal variation alone can evoke the essence of place and time.",
    details: "Watercolor on paper\nDimensions: 21 x 29.7 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/watercolor-urban-spire.jpeg", "/images/watercolor-urban-spire.jpeg"],
    related: ["34", "35", "29"],
  },
  {
    id: "34",
    title: "Historic Quarter",
    category: "Original Watercolor",
    price: "2,200.00",
    description:
      "A sophisticated monochromatic watercolor depicting a historic town center with a prominent civic building and bell tower. The artist employs a limited palette of grays to create a compelling study of architectural forms and spatial relationships. The composition balances detailed architectural elements with looser, more gestural treatment of the foreground structures, creating visual interest and depth. The confident brushwork suggests market stalls or temporary structures in the foreground, adding a sense of daily life to the scene. The painting demonstrates how value contrast and compositional structure can create a powerful sense of place even without color.",
    details: "Watercolor on paper\nDimensions: 21 x 29.7 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/watercolor-urban-buildings.jpeg", "/images/watercolor-urban-buildings.jpeg"],
    related: ["33", "35", "7"],
  },
  {
    id: "35",
    title: "Tower Perspective",
    category: "Original Watercolor",
    price: "2,300.00",
    description:
      "A dramatic monochromatic watercolor depicting a narrow urban street with a striking view of a tower or spire in the distance. The composition employs strong perspective lines created by the buildings on either side to draw the eye toward the central architectural feature. The artist masterfully handles values to create a sense of depth and atmosphere, with darker tones in the foreground buildings gradually lightening toward the distant tower. Subtle suggestions of figures at street level add a human element and sense of scale to the scene. The painting demonstrates how careful control of value and perspective can create a powerful sense of space and drama.",
    details: "Watercolor on paper\nDimensions: 21 x 29.7 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/watercolor-urban-tower.jpeg", "/images/watercolor-urban-tower.jpeg"],
    related: ["33", "34", "7"],
  },
  // Nuevas acuarelas urbanas con color
  {
    id: "36",
    title: "Urban Street with Dome",
    category: "Original Watercolor",
    price: "2,450.00",
    description:
      "A vibrant watercolor painting capturing the essence of an urban street scene. The composition features historic architecture with a distinctive green-domed building as the focal point, with a yellow taxi and red vehicle adding life and movement to the scene. The artist skillfully balances architectural detail with loose, expressive brushwork, creating a sense of immediacy and urban vitality. The interplay of cool grays and blues of the buildings against the warm yellows and reds of the vehicles demonstrates masterful color harmony and creates visual excitement while maintaining compositional unity.",
    details: "Watercolor on paper\nDimensions: 24 x 32 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/watercolor-urban-street-dome.jpeg", "/images/watercolor-urban-street-dome.jpeg"],
    related: ["37", "38", "33"],
  },
  {
    id: "37",
    title: "Cathedral Plaza",
    category: "Original Watercolor",
    price: "2,550.00",
    description:
      "An atmospheric watercolor depicting a grand cathedral or church complex with multiple domes and a bell tower. The painting captures the monumental scale of religious architecture through careful attention to proportion and perspective. The artist employs a sophisticated palette of earth tones—ochres, umbers, and muted greens—punctuated by the warm terracotta tones of the building facades. The foreground suggests the presence of daily life with hints of vehicles and urban activity, creating a dialogue between the sacred and secular. The loose, confident brushwork allows the architecture to emerge from the paper with both solidity and atmospheric lightness.",
    details: "Watercolor on paper\nDimensions: 24 x 32 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/watercolor-cathedral-plaza-vertical.jpeg", "/images/watercolor-cathedral-plaza-vertical.jpeg"],
    related: ["36", "38", "34"],
  },
  {
    id: "38",
    title: "Countryside Vista",
    category: "Original Watercolor",
    price: "2,750.00",
    description:
      "A serene watercolor landscape that captures the peaceful beauty of the countryside through the frame of a prominent tree. The composition uses the dark silhouette of the tree trunk and branches to create a natural window onto rolling hills and distant mountains. The artist demonstrates exceptional skill in rendering atmospheric perspective, with the landscape receding through subtle color temperature shifts from warm foreground tones to cool distant blues and purples. The painting exemplifies the classical landscape tradition while maintaining a fresh, contemporary sensibility through its loose, confident brushwork and harmonious color palette.",
    details: "Watercolor on paper\nDimensions: 24 x 32 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/watercolor-countryside-vista-new.jpeg", "/images/watercolor-countryside-vista-new.jpeg"],
    related: ["26", "29", "36"],
  },
  {
    id: "39",
    title: "Canal Bridge Reflections",
    category: "Original Watercolor",
    price: "2,850.00",
    description:
      "A masterful watercolor depicting a charming European canal scene with a stone bridge and historic architecture. The composition features a beautiful stone arch bridge spanning calm waters, with traditional buildings including a distinctive round tower with a conical roof. The artist demonstrates exceptional skill in capturing the reflective quality of the water, which mirrors the buildings and sky above. The palette is dominated by soft blues and grays that create a serene, contemplative atmosphere, while warm earth tones in the architecture provide subtle contrast. The delicate handling of light and shadow, combined with the fluid transparency characteristic of watercolor, creates a sense of timeless tranquility that invites the viewer to pause and appreciate the quiet beauty of this historic setting.",
    details: "Watercolor on paper\nDimensions: 32 x 42 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/watercolor-canal-bridge.jpeg", "/images/watercolor-canal-bridge.jpeg"],
    related: ["33", "34", "36"],
  },
  // New coastal watercolor
  {
    id: "57",
    title: "Coastal Bay with Boats",
    category: "Original Watercolor",
    price: "2,950.00",
    description:
      "A captivating watercolor seascape depicting a tranquil coastal bay with fishing boats anchored in crystal-clear turquoise waters. The composition masterfully captures the Mediterranean atmosphere with its dramatic rocky coastline rising from the sea. The artist demonstrates exceptional skill in rendering the transparency and luminosity of the water, using various shades of turquoise and green that seem to glow on the paper. The sandy beach in the foreground shows subtle traces of human activity, while the boats provide focal points that draw the eye across the composition. The overcast sky, rendered in soft grays, creates a perfect contrast to the vibrant waters below, enhancing the overall sense of coastal serenity.",
    details: "Watercolor on paper\nDimensions: 32 x 45 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/watercolor-coastal-boats.jpeg", "/images/watercolor-coastal-boats.jpeg"],
    related: ["39", "30", "7"],
  },
  // New countryside watercolor with tree
  {
    id: "61",
    title: "Verdant Meadow",
    category: "Original Watercolor",
    price: "2,750.00",
    description:
      "A luminous watercolor landscape capturing the essence of rural tranquility through masterful brushwork and atmospheric perspective. The composition features a prominent tree in the foreground, its lush green foliage rendered with confident, expressive strokes that demonstrate the artist's command of the watercolor medium. Golden fields stretch toward distant blue-gray mountains, creating a sense of depth and space that draws the viewer into the pastoral scene. The sky, painted in soft blue and gray washes, suggests a partly cloudy day with gentle, diffused light. The artist's sophisticated understanding of color temperature and atmospheric effects is evident in the way warm earth tones in the foreground gradually transition to cooler blues and purples in the distance, creating a convincing sense of three-dimensional space on the two-dimensional surface.",
    details: "Watercolor on paper\nDimensions: 32 x 45 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/watercolor-countryside-tree.jpeg", "/images/watercolor-countryside-tree.jpeg"],
    related: ["26", "38", "9"],
  },
  // Drawings - Sentimiento al desnudo collection in the correct order
  {
    id: "62",
    title: "Eco",
    category: "Original Drawing - Sentimiento al desnudo",
    price: "SOLD",
    details:
      "SOLD\nGraphite on paper\nDimensions: 70 x 47 cm\nYear: 2021\nFrom the solo exhibition 'Sentimiento al desnudo'\nSigned by the artist",
    images: ["/images/drawing-eco-eco.jpeg", "/images/drawing-eco-eco.jpeg"],
    related: ["63", "64", "65"],
  },
  {
    id: "63",
    title: "Sin título",
    category: "Original Drawing - Sentimiento al desnudo",
    price: "not-for-sale",
    details:
      "Charcoal on paper\nDimensions: 76 x 54 cm\nYear: 2021\nFrom the solo exhibition 'Sentimiento al desnudo'\nSigned by the artist",
    images: ["/images/drawing-sin-titulo.jpeg", "/images/drawing-sin-titulo.jpeg"],
    related: ["62", "64", "65"],
  },
  {
    id: "64",
    title: "Silueta en claro obscuro",
    category: "Original Drawing - Sentimiento al desnudo",
    price: "not-for-sale",
    details:
      "Pastel on paper\nDimensions: 54 x 76 cm\nYear: 2021\nFrom the solo exhibition 'Sentimiento al desnudo'\nSigned by the artist",
    images: ["/images/drawing-silueta-claro-obscuro.jpeg", "/images/drawing-silueta-claro-obscuro.jpeg"],
    related: ["62", "63", "65"],
  },
  {
    id: "65",
    title: "Flor de Cerezo",
    category: "Original Drawing - Sentimiento al desnudo",
    price: "not-for-sale",
    details:
      "Pastel on paper\nDimensions: 76 x 54 cm\nYear: 2021\nFrom the solo exhibition 'Sentimiento al desnudo'\nSigned by the artist",
    images: ["/images/drawing-flor-de-cerezo.jpeg", "/images/drawing-flor-de-cerezo.jpeg"],
    related: ["62", "63", "64"],
  },
  {
    id: "66",
    title: "Luciérnaga",
    category: "Original Drawing - Sentimiento al desnudo",
    price: "SOLD",
    details:
      "SOLD\nPastel on paper\nDimensions: 76 x 54 cm\nYear: 2021\nFrom the solo exhibition 'Sentimiento al desnudo'\nSigned by the artist",
    images: ["/images/drawing-luciernaga.jpeg", "/images/drawing-luciernaga.jpeg"],
    related: ["62", "63", "64"],
  },
  // New Paintings Category
  {
    id: "40",
    title: "Abstract Figures in Motion",
    category: "Original Painting",
    price: "3,200.00",
    description: "",
    details: "Acrylic on canvas\nDimensions: 60 x 80 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/painting-abstract-figures-new.jpeg", "/images/painting-abstract-figures-new.jpeg"],
    related: ["41", "42", "43"],
  },
  {
    id: "41",
    title: "Golden Expression",
    category: "Original Painting",
    price: "2,950.00",
    description: "",
    details: "Acrylic on canvas\nDimensions: 50 x 70 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/painting-golden-expression.jpeg", "/images/painting-golden-expression.jpeg"],
    related: ["40", "42", "44"],
  },
  {
    id: "42",
    title: "Casiopea",
    category: "Original Painting",
    price: "3,100.00",
    description: "",
    details: "Mixed media on canvas\nDimensions: 70 x 90 cm\nYear: 2017\nSigned by the artist",
    images: ["/images/painting-dark-abstraction.jpeg", "/images/painting-dark-abstraction.jpeg"],
    related: ["40", "41", "45"],
  },
  {
    id: "43",
    title: "Serpiente Emplumada",
    category: "Original Painting",
    price: "2,800.00",
    description: "",
    details: "Mixed media on paper\nDimensions: 27 x 38 cm\nYear: 2022\nSigned by the artist",
    images: ["/images/painting-organic-flow.jpeg", "/images/painting-organic-flow.jpeg"],
    related: ["41", "44", "46"],
  },
  {
    id: "44",
    title: "Yellow Energy",
    category: "Original Painting",
    price: "2,750.00",
    description: "",
    details: "Mixed media on canvas\nDimensions: 65 x 85 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/painting-yellow-energy.jpeg", "/images/painting-yellow-energy.jpeg"],
    related: ["41", "43", "47"],
  },
  {
    id: "45",
    title: "Preludio de Girón",
    category: "Original Painting",
    price: "3,000.00",
    description: "",
    details: "Mixed media on paper\nDimensions: 77 x 62 cm\nYear: 2015\nSigned by the artist",
    images: ["/images/painting-geometric-composition.jpeg", "/images/painting-geometric-composition.jpeg"],
    related: ["42", "46", "47"],
  },
  {
    id: "46",
    title: "Gestural Marks",
    category: "Original Painting",
    price: "2,650.00",
    description: "",
    details: "Acrylic on canvas\nDimensions: 50 x 65 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/painting-gestural-marks.jpeg", "/images/painting-gestural-marks.jpeg"],
    related: ["43", "45", "47"],
  },
  {
    id: "47",
    title: "Altar",
    category: "Original Painting",
    price: "2,900.00",
    description: "",
    details: "Mixed media on paper\nDimensions: 66 x 77 cm\nYear: 2015\nSigned by the artist",
    images: ["/images/painting-still-life-modern.jpeg", "/images/painting-still-life-modern.jpeg"],
    related: ["44", "46", "49"],
  },
  {
    id: "49",
    title: "Bull Silhouette",
    category: "Original Painting",
    price: "3,400.00",
    description: "",
    details: "Mixed media on paper\nDimensions: 70 x 100 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/painting-bull-silhouette.jpeg", "/images/painting-bull-silhouette.jpeg"],
    related: ["40", "42", "47"],
  },
  {
    id: "50",
    title: "Vibrant Landscape",
    category: "Original Painting",
    price: "3,250.00",
    description: "",
    details: "Acrylic on paper\nDimensions: 47 x 35 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/painting-vibrant-landscape.jpeg", "/images/painting-vibrant-landscape.jpeg"],
    related: ["41", "44", "49"],
  },
  {
    id: "51",
    title: "Otoño",
    category: "Original Painting",
    price: "3,800.00",
    description: "",
    details: "Acrylic on paper\nDimensions: 90 x 120 cm\nYear: 2023\nSigned by the artist",
    images: ["/images/painting-abstract-expressionist.jpeg", "/images/painting-abstract-expressionist.jpeg"],
    related: ["40", "42", "50"],
  },
  // Still Life Series - Four paintings of the same motif
  {
    id: "52",
    title: "Naturaleza Muerta I",
    category: "Original Painting",
    price: "3,500.00",
    description: "",
    details: "Acrylic on paper\nDimensions: 60 x 40 cm\nYear: 2022\nSigned by the artist",
    images: ["/images/painting-still-life-series-1.jpeg", "/images/painting-still-life-series-1.jpeg"],
    related: ["53", "54", "55"],
  },
  {
    id: "53",
    title: "Naturaleza Muerta II",
    category: "Original Painting",
    price: "3,500.00",
    description: "",
    details: "Acrylic on paper\nDimensions: 60 x 40 cm\nYear: 2022\nSigned by the artist",
    images: ["/images/painting-still-life-series-2.jpeg", "/images/painting-still-life-series-2.jpeg"],
    related: ["52", "54", "55"],
  },
  {
    id: "54",
    title: "Naturaleza Muerta III",
    category: "Original Painting",
    price: "3,500.00",
    description: "",
    details: "Acrylic on paper\nDimensions: 60 x 40 cm\nYear: 2022\nSigned by the artist",
    images: ["/images/painting-still-life-series-3.jpeg", "/images/painting-still-life-series-3.jpeg"],
    related: ["52", "53", "55"],
  },
  {
    id: "55",
    title: "Naturaleza Muerta IV",
    category: "Original Painting",
    price: "3,500.00",
    description: "",
    details: "Acrylic on paper\nDimensions: 60 x 40 cm\nYear: 2022\nSigned by the artist",
    images: ["/images/painting-still-life-series-4.jpeg", "/images/painting-still-life-series-4.jpeg"],
    related: ["52", "53", "54"],
  },
  // New action painting
  {
    id: "58",
    title: "Dynamic Action",
    category: "Original Painting",
    price: "4,800.00",
    description: "",
    details: "Mixed media on canvas\nDimensions: 120 x 90 cm\nYear: 2024\nSigned by the artist",
    images: ["/images/painting-abstract-action.jpeg", "/images/painting-abstract-action.jpeg"],
    related: ["40", "51", "42"],
  },
  // New abstract painting with green and pink
  {
    id: "59",
    title: "Emerald Dreams",
    category: "Original Painting",
    price: "3,650.00",
    description: "",
    details: "Mixed media on canvas\nDimensions: 70 x 90 cm\nYear: 2024\nSigned by the artist",
    images: ["/images/painting-abstract-green-pink.jpeg", "/images/painting-abstract-green-pink.jpeg"],
    related: ["40", "51", "58"],
  },
  // New painting with three figures
  {
    id: "60",
    title: "Three Figures in Motion",
    category: "Original Painting",
    price: "4,200.00",
    description: "",
    details: "Mixed media on paper\nDimensions: 50 x 70 cm\nYear: 2024\nSigned by the artist",
    images: ["/images/painting-three-figures.jpeg", "/images/painting-three-figures.jpeg"],
    related: ["40", "58", "59"],
  },
]
